# Site wide configuration

title: Mathemathinking
locale: en_US
description: Math, Data, Machine learning, Chemical engineering
logo: cover.jpeg
search: true
 # url: http://localhost:4000
url: http://CorySimon.github.io

# Jekyll configuration

permalink:   /:categories/:title/
 # markdown:    redcarpet
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true
# Site owner
owner:
  name: Cory Simon
  avatar: cory.jpg
  email: CoryMSimon@gmail.com
  disqus-shortname: corysimongithubio
  twitter: CoryMSimon
  facebook: cory.simon.589
  github: CorySimon
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: 
  flickr: #username
  tumblr: #username
  google: #username
    plus: #username
    analytics: CoryMSimon
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
